### ISSUE TITLE
Define Configuration File Structure

### ISSUE THREAD

**Issue by Hbbb** [quinn/whos-home#1]
Each Pi installation will require a configuration file to configure some things. Here's the initial concept I came up with:
```yaml
queue_id: wkeljlk3j4kl3j43
queue_name: whos-home-queue-dave
following:
  - name: Harrison
    location_name: Home
    gpio_pin_number: 48

  - name: Kyle
    location_name: Home
    gpio_pin_number: 53

  - name: Mom
    location_name: Home
    gpio_pin_number: 87
```
